// to be organized

import { cn } from "@/lib/utils";
import { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
<<<<<<< HEAD
import "@/app/globals.css";
import Image from "next/image";
import bg from "@/public/auth-background.png";
const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
export default function Layout({ children }: { children: React.ReactNode }) {
=======
import "@/app/globals.css"
const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function Layout({children}: {children: React.ReactNode}) {
>>>>>>> 247ce7b085ad8271f53ade34154f8c66b005cdbf
    return (
        <html
            lang="en"
            className={cn(
<<<<<<< HEAD
=======
                "h-full",
>>>>>>> 247ce7b085ad8271f53ade34154f8c66b005cdbf
                "antialiased",
                geistSans.variable,
                geistMono.variable,
                "font-sans",
                inter.variable,
            )}
        >
<<<<<<< HEAD
            <body className="flex flex-col">
                <Image
                    className="h-screen w-full object-cover object-top m-0 fixed -z-10 contrast-30 blur-xs brightness-200"
                    alt="background"
                    src={bg}
                ></Image>
                {children}
            </body>
=======
            <body className="min-h-full flex flex-col">{children}</body>
>>>>>>> 247ce7b085ad8271f53ade34154f8c66b005cdbf
        </html>
    );
}
