import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "@/app/globals.css";
import { cn } from "@/lib/utils";
import {
    Sidebar,
    SidebarContent,
    SidebarFooter,
    SidebarGroup,
    SidebarHeader,
    SidebarInset,
    SidebarProvider,
    SidebarTrigger,
} from "@/components/ui/sidebar";
import Image from "next/image";
import Logo from "@/public/logo.png";
import CustomSidebarMenu from "@/custom-components/menu/custom-sidebar-menu";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={cn(
                "h-full",
                "antialiased",
                geistSans.variable,
                geistMono.variable,
                "font-sans",
                inter.variable,
            )}
        >
            <body className="min-h-full max-w-full overflow-x-hidden flex flex-col">
                <SidebarProvider>
                    <Sidebar className="shadow-2xl ">
                        <SidebarHeader className="flex flex-col bg-white">
                            <div className="flex flex-row items-center">
                                <Image
                                    className="size-24 mix-blend-multiply"
                                    alt="App Logo"
                                    src={Logo}
                                    priority
                                />
                                <p className="text-sm">
                                    a Fullstack Portfolio by Assaifydeveloper
                                </p>
                            </div>
                        </SidebarHeader>
                        <hr />
                        <SidebarContent className="bg-white">
                            <SidebarGroup className="p-6">
                                <p className="text-sm">Hi, Username</p>
                                <p className="text-xs text-gray-600">
                                    Admin Role
                                </p>
                            </SidebarGroup>
                            <hr />
                            <SidebarGroup>
                                <CustomSidebarMenu role="admin" />
                            </SidebarGroup>
                        </SidebarContent>
                        <SidebarFooter />
                    </Sidebar>
                    <SidebarInset className="bg-gray-200">
                        <SidebarTrigger className="fixed" />
                        {children}
                    </SidebarInset>
                </SidebarProvider>
            </body>
        </html>
    );
}
